name: Telestal
version: '${project.version}'
main: net.ariremi.telestal.Telestal
authors: [ BurstLime ]
depend: [ HolographicDisplays, ProtocolLib ]
commands:
  telestal:
    aliases: [ ts ]
    description: メインコマンド
    usage: /<command> help
    default: op
